name = "Drill"
author = "SkywardMC"
version = "0.7.0-1.32.0+1.20.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26fbe7475c8fdb2091b1a47043fe9b0f8b97880edc0cf1f6fb4e3c91da624131"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.105"
